### ISSUE TITLE
Some suggestions for improvement

### ISSUE THREAD

**Issue by merlinuwe** [zhouhua/obsidian-export-image#23]
I'm so happy that your plugin finally runs again.

Here are some suggestions for improvements:

- Some of my images are meant to be exported very large. (They contain images and graphics that are to be printed razor-sharp in 300 px per inch on DIN A4 and DIN A3 paper.) Is it possible to widen the output width (image width) accordingly in order to enable the sharpest possible representation? 

I saw, that with an image width of 640 px (default) I get an 1244 px width image.

- The dialog windows could be a bit wider to better show the contents and to avoid the horizontal scroll bar (and perhaps the vertical scrollbar, too).

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/19a5e1aa-36b4-46fd-b1e0-99ca327a34cf)

- An optional menu entry "Export to image".

Thanks again for your great plugin.

**Comment by zhouhua** [comment]
In fact, you can enter a large width value in this input. 

In order to make the image clearer, the exported image of this plugin is actually twice the resolution, which can make the exported image sharper on high PPI screens (such as mobile phones). You mentioned setting the width to 640, but exported the width to 1244 instead of 1280, which may be a potential bug. I will confirm it later.

As for whether to increase the width of the dialog box, my idea may be different. Simply adjusting the size of the dialog box cannot meet all scenarios.  I think a more reasonable way is similar to image preview, which can be directly dragged with the mouse and easily zoomed in and out. Currently, the preview area in the dialog box is not an image. In order to have better responsiveness when adjusting the width, I did not generate an image immediately when adjusting the width, but clicked the button below to generate the image. I think maybe I can try to present the final image directly during the preview.

The last suggestion is great, I will try to add this feature.

**Comment by merlinuwe** [comment]
Your idea is better than mine. ;-)

**Comment by zhouhua** [comment]
Today I developed the features of your proposal. You can try the 2.1.0 version. In the preview interface, you can move and zoom the image (no scroll bars). I also added a function entry in the editor menu: 

![image](https://github.com/zhouhua/obsidian-export-image/assets/2276598/25751631-3759-4293-a0c1-76c11f26dcc8)

**Comment by merlinuwe** [comment]
Well made, thank you very much.


During testing, I found that unchecking the "Including file name as title" checkbox has no effect. The title is _always_ at the top of the output.

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/5ad09f6c-860c-42ae-a907-8686bc3b773c)

Are you still thinking about the scaling of the pixels? I set "Image width" to 1000 but I get 1964. When set to 2000 I get 3964. With the default of 640 I get 1244.

Cosmetics: I cannot completely delete the number with the backspace key. A zero (0) remains.

![image](https://github.com/zhouhua/obsidian-export-image/assets/4138869/67104df3-3cbb-4a5d-9baa-c8dc988ab9ef)

**Comment by zhouhua** [comment]
> During testing, I found that unchecking the "Including file name as title" checkbox has no effect. The title is always at the top of the output.

It works fine on my computer:

![image](https://github.com/zhouhua/obsidian-export-image/assets/2276598/659d6acb-7aac-4e42-abe2-f1b64ccbb3b6)

Can you help me take a screenshot to see what the editor view looks like?

> Are you still thinking about the scaling of the pixels? I set "Image width" to 1000 but I get 1964. When set to 2000 I get 3964. With the default of 640 I get 1244.

I guess the scroll bar on the right side is interfering with the calculation. I tested it on a mac, and the scroll bar on the mac is floating above the element, so it does not affect the width calculation. I will do some compatibility later for this situation.

> Cosmetics: I cannot completely delete the number with the backspace key. A zero (0) remains.

My initial idea may have been a bit over-designed, but I think I can let go of the limitations of Input.

**Comment by zhouhua** [comment]
I just released a new version that solves the problem of width input and also tries to fix the scroll bar problem on Windows, but I am not sure if it works because I don't have a Windows computer at the moment.

**Comment by merlinuwe** [comment]
Looks far better, now.

If I give 5000 px I get 9966 px.
It I give 10000 px I get 19966 px.

The issue with the not deletable 0 is solved.
