### ISSUE TITLE
Q&E: What does metadata stand for?

### ISSUE THREAD

**Issue by DoTrONoL** [zhouhua/obsidian-export-image#30]
I'm asking for a description in "Show metadata" switch.

I couldn't figure out what it does represent, ~just as others may have the same question as me,~ so I'm asking you an example and an enhancement.

Also, thx by the plugin, you're awesome!

![image](https://github.com/zhouhua/obsidian-export-image/assets/71497422/84cc7058-fe7f-471c-b0cd-7af91b3ddcb8)

**Comment by zhouhua** [comment]
Obsidian metadata is a feature similar to Notion's property. You can refer to this document to learn more: https://help.obsidian.md/Editing+and+formatting/Properties .

#26  In this issue, some users believe that metadata should also be part of the document, and in some scenarios, they also hope to export images together. I partially agree with this view, so I have made limited implementations for metadata, but it is not exported by default. Users need to enable this function in the plugin settings.

It is worth mentioning that the metadata of Obsidian notes is sometimes not just static information, but also has certain functionality. For example, there is a built-in cssClasses property, which can add specific classes to specific documents, so that users can achieve different display effects for different notes through custom CSS (my plugin also supports this); and popular Obsidian plugins like [obsidian-banners](https://github.com/noatpad/obsidian-banners) also define the hero image of the note through the banner property in metadata. However, due to the wide range of uses of metadata, I cannot ensure that everything is as expected by users in my plugin.
