### ISSUE TITLE
ASCII char 5 breaks the plugin

### ISSUE THREAD

**Issue by TheBestPessimist** [zhouhua/obsidian-export-image#34]
![image](https://github.com/zhouhua/obsidian-export-image/assets/4482210/a2eec71d-2d66-4d2e-ab34-cb4e7668170d)
When i click the button <kbd>Copy to Clipboard</kbd> or the save button, i get this error. Nothing more.

Anything i can give you extra?

**Comment by zhouhua** [comment]
Sorry, I can't reproduce the issue.

Could you share your list of plugins with me, so I can check for any potential conflicts between them?

Or you could help by disabling the other plugins to quickly determine if there is a conflict.

**Comment by TheBestPessimist** [comment]
With all the community plugins disabled i still ahve the error:
![image](https://github.com/zhouhua/obsidian-export-image/assets/4482210/7fa45a58-2c2f-4627-ad2d-d5cb1d011ef1)

**Comment by TheBestPessimist** [comment]
I have found the problem: this file contains the ascii character 5. 
If you delete that, making an image works, if you bring it back in, it will throw error
[EFUL-257 - Copy.md](https://github.com/zhouhua/obsidian-export-image/files/14959529/EFUL-257.-.Copy.md)

**Comment by zhouhua** [comment]
Great, I'll look into it and fix it as soon as possible.

**Comment by zhouhua** [comment]
I've made some attempts but haven't found a perfect way to preserve these invisible characters. As a compromise, I've had to remove these characters when generating the images.

**Comment by TheBestPessimist** [comment]
removing is acceptable too. but i want to ask what are _these characters_ ?

**Comment by zhouhua** [comment]
For information about what these characters are, I think you can refer to this link: https://en.wikipedia.org/wiki/Control_character .

I don't know why they appeared in your note, but I think there are two likely reasons. First, they could have been copied and pasted from somewhere else. Since these characters are invisible, we usually don't realize they're there. Second, as mentioned in the link above, some keyboards can input these invisible characters. For example, 0x05 can be inputted by pressing Ctrl + E (though my input method doesn't have this feature).

**Comment by TheBestPessimist** [comment]
They appeared in my note because i pasted them there. I was doing a post-mortem and saved some messages one of my system consumes. Those messages have a machine readable structure where the delimitator between fields is that ASCII char 5.

For the record, in Obsidian, the characters are displayed as a square and that would have been ok too: 
![image](https://github.com/zhouhua/obsidian-export-image/assets/4482210/03dfcf63-9649-4432-a0ca-77cf710717f7)
