### ISSUE TITLE
Support more image sizing/sizing template

### ISSUE THREAD

**Issue by thatswiftdev** [zhouhua/obsidian-export-image#64]
I just found this plugin is a hidden gem. And I really enjoy using it. However, there is only one problem for myself, that I can't specify the height of the image. It would be great to add this support, or maybe create a template size for Instagram Story, Post etc. Because I'm planning to upload some of my writings to social media.

Thanks you very much!

**Comment by zhouhua** [comment]
This plugin allows you to adjust the image width, while the image height is determined by the length of the note content. Based on the current features provided by the plugin, I think you can select a portion of the note content and choose "Export selected content as image" to share part of the content, rather than adjusting the image height.
